[tool.mypy]
cache_dir = "build/.cache/mypy"
sqlite_cache = true
python_version = "3.12"
strict = true

[tool.pytest.ini_options]
cache_dir = "build/.cache/pytest"

[tool.ruff]
cache-dir = "build/.cache/ruff"
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "A003",   # https://docs.astral.sh/ruff/rules/builtin-attribute-shadowing/
  "ANN101", # https://docs.astral.sh/ruff/rules/missing-type-self/
  "COM812", # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
  "D",      # https://docs.astral.sh/ruff/rules/#pydocstyle-d
  "E501",   # https://docs.astral.sh/ruff/rules/line-too-long/
  "ISC001", # https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/
  "T201",   # https://docs.astral.sh/ruff/rules/print/
]
[tool.ruff.lint.per-file-ignores]
"test_*.py" = [
  "S101",   # https://docs.astral.sh/ruff/rules/assert/
  "INP001", # https://docs.astral.sh/ruff/rules/implicit-namespace-package/
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
